Add pr content type
NyalaDev/edu-backend pull request #20
Opened 2021-03-09 14:55 UTC by alaa-yahia

2021-03-09 18:05 UTC, kabaros commented on api/pr/controllers/pr.js
> +    console.log(entity, 'entity');
please remove this in the next PR .. if you want to log, then use `strapi.log.debug(....)` or `.error` etc.. if it was just for testing then remove it

2021-03-09 18:06 UTC, kabaros requested changes
one small change .. also shouldn't there be an update to bootstrap permissions, so that only authenticated role is allowed to perform these actions?

2021-03-09 18:17 UTC, alaa-yahia commented
> one small change .. also shouldn't there be an update to bootstrap permissions, so that only authenticated role is allowed to perform these actions?

Where is this permission file? I changed it from admin panel

2021-03-10 06:47 UTC, kabaros approved these changes

2021-03-10 06:48 UTC, merged